---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.13.5
        envFrom:
          - secretRef:
              name: godaddy-cred
        args:
        - --source=service # ingress is also possible
        - --source=ingress
        - --domain-filter=devops-scenarios.online # (optional) limit to only example.com domains; change to match the zone created above.
        - --provider=godaddy
        #- --txt-prefix=glab-prod. # In case of multiple k8s cluster
        #- --txt-owner-id=glab-prod # In case of multiple k8s cluster
        - --godaddy-api-key=$(GoDaddyAPIKey)
        - --godaddy-api-secret=$(GoDaddySecretKey)
        - --exclude-target-net=192.168.0.0/16
