apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-express
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/aeldakhli/DevOps_project.git'
    targetRevision: main
    path: helm-charts/mongo-express/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: custom-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true