apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-main
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: v1.12.2
    helm:
      releaseName: cert-manager
      valueFiles:
      - $values/helm-charts/cert-manager/values.yaml
  - repoURL: 'https://github.com/aeldakhli/DevOps_project.git'
    targetRevision: main
    ref: values
  - repoURL: 'https://github.com/aeldakhli/DevOps_project.git'
    targetRevision: main
    path: helm-charts/cert-manager/manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
